x-airflow-common:
  &airflow-common
  image: apache/airflow:2.10.2-python3.10
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/db/airflow.db
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: '3'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- pandas numpy scikit-learn joblib statsmodels scipy kedro~=0.19.11 kedro-datasets matplotlib seaborn}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./src:/opt/airflow/src
    - ./pyproject.toml:/opt/airflow/pyproject.toml
    - airflow-db:/opt/airflow/db
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    airflow-init:
      condition: service_completed_successfully

services:
  airflow-init:
    <<: *airflow-common
    user: "0:0"
    entrypoint: /bin/bash
    # Override inherited depends_on to avoid self-dependency cycle
    depends_on: {}
    command:
      - -c
      - |
        mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins /opt/airflow/db
        mkdir -p /opt/airflow/data/02_intermediate /opt/airflow/data/03_primary /opt/airflow/data/05_model_input /opt/airflow/data/06_models /opt/airflow/data/07_model_output /opt/airflow/data/08_reports
        chown -R 50000:0 /opt/airflow
        pip install -e /opt/airflow
        airflow db migrate
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
        chown -R 50000:0 /opt/airflow
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}

  airflow-webserver:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install -e /opt/airflow
        exec airflow webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on

  airflow-scheduler:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install -e /opt/airflow
        exec airflow scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on

volumes:
  airflow-logs:
  airflow-plugins:
  airflow-db:
