# DVC Pipeline Configuration
# Defines stages for data versioning and experiment tracking

stages:
  data_engineering:
    cmd: kedro run --pipeline=data_engineering
    deps:
      - data/01_raw/df_Customers.csv
      - data/01_raw/df_Orders.csv
      - data/01_raw/df_OrderItems.csv
      - src/proyecto_ml/pipelines/data_engineering/
    outs:
      - data/02_intermediate/:
          cache: true
      - data/03_primary/:
          cache: true
      - data/05_model_input/model_input.csv:
          cache: true
      - data/05_model_input/model_input_with_target.csv:
          cache: true
      - data/05_model_input/model_input_encoded.csv:
          cache: true
      - data/05_model_input/X_train.csv:
          cache: true
      - data/05_model_input/X_test.csv:
          cache: true
      - data/05_model_input/y_train.csv:
          cache: true
      - data/05_model_input/y_test.csv:
          cache: true
      - data/05_model_input/X_clf_train.csv:
          cache: true
      - data/05_model_input/X_clf_test.csv:
          cache: true
      - data/05_model_input/y_clf_train.csv:
          cache: true
      - data/05_model_input/y_clf_test.csv:
          cache: true
    metrics:
      - data/08_reports/model_input_stats.csv:
          cache: false
      - data/08_reports/model_input_missing.csv:
          cache: false

  classification:
    cmd: kedro run --pipeline=classification
    deps:
      - data/05_model_input/X_clf_train.csv
      - data/05_model_input/X_clf_test.csv
      - data/05_model_input/y_clf_train.csv
      - data/05_model_input/y_clf_test.csv
      - src/proyecto_ml/pipelines/classification/
    outs:
      - data/06_models/classification_trained_models.pkl:
          cache: true
    params:
      - classification.cv_folds
      - classification.random_state
      - classification.n_jobs
    metrics:
      - data/07_model_output/classification_metrics_extended.csv:
          cache: false
      - data/07_model_output/classification_confusion_matrices_extended.csv:
          cache: false
      - data/07_model_output/classification_feature_importances_extended.csv:
          cache: false

  regression:
    cmd: kedro run --pipeline=regression
    deps:
      - data/05_model_input/X_train.csv
      - data/05_model_input/X_test.csv
      - data/05_model_input/y_train.csv
      - data/05_model_input/y_test.csv
      - src/proyecto_ml/pipelines/regression/
    outs:
      - data/06_models/regression_trained_models.pkl:
          cache: true
    params:
      - regression.cv_folds
      - regression.random_state
      - regression.n_jobs
    metrics:
      - data/07_model_output/regression_metrics_extended.csv:
          cache: false
      - data/07_model_output/regression_feature_importances_extended.csv:
          cache: false

  data_science:
    cmd: kedro run --pipeline=data_science
    deps:
      - data/03_primary/full_orders.csv
      - src/proyecto_ml/pipelines/data_science/
    outs:
      - data/06_models/rf_model.pkl:
          cache: true
    params:
      - data_science.max_rows
      - data_science.test_size
      - data_science.random_state
      - data_science.cv_folds
    metrics:
      - data/07_model_output/model_metrics.csv:
          cache: false
      - data/07_model_output/regression_metrics.csv:
          cache: false
      - data/07_model_output/classification_metrics.csv:
          cache: false
      - data/07_model_output/classification_confusion_matrices.csv:
          cache: false
      - data/07_model_output/feature_importances.csv:
          cache: false
      - data/07_model_output/classification_feature_importances.csv:
          cache: false
