data_science:
  max_rows: 5000
  test_size: 0.2
  random_state: 42
  cv_folds: 3
  sample_frac: 0.2

classification:
  cv_folds: 3
  random_state: 42
  n_jobs: -1
  sample_size: 3000

regression:
  cv_folds: 3
  random_state: 42
  n_jobs: -1
  sample_size: 3000
